### ISSUE TITLE
phylesystem study retrieval returns web2py error

### ISSUE THREAD

**Issue by pmidford** [OpenTreeOfLife/phylesystem-api#150]
I noticed during this morning's statistics call that the cronjob had, in fact died on June 10.  When I ran the script from the command line it failed immediately and I was able to track the failing request and replicate with this curl call.  
curl http://devapi.opentreeoflife.org/v2/study/pg_2379/

Was this study removed, or did something else change?

**Comment by snacktavish** [comment]
The error for the web-2py log on devapi  includes
  "<type 'exceptions.ValueError'> No git repos in ['REPO_PAR']"
and the config file in phylesystem-api/private/config does just set the repo parent as "REPO_PAR". 

I'm not up on current deployment though, so I'm not sure if that was supposed to get set elsewhere in the deployment process or which of the several phylesystem repos on devapi it should be pointing to.

**Comment by jimallman** [comment]
> No git repos in ['REPO_PAR']

Argh, this is a problem with the current deployment, because of recent changes (not yet merged) to the server-config files. Now that we're cloning repos for other data like tree collections, we needed better variables like `PHYLESYSTEM_REPO_PAR` and `COLLECTIONS_REPO_PAR` to distinguish between them.

I'll try to clean this up in the next week, perhaps by merging the new variables into all major branches of `phylesystem-api` and `opentree`. Assigning this to myself...

For now, devapi should **always** be deployed using the 'master' branch of opentree. (In other words, checkout opentree/master, then use its `push.sh` script to deploy as usual.)

I've just re-deployed phylesystem-api from opentree/master, and the web2py config shows a sensible path:
```config
repo_parent   = /home/opentree/repo/phylesystem-0_par
```

**Comment by pmidford** [comment]
This seems to be working now - the statistics jobs started working after the build was fixed.
