### ISSUE TITLE
Should outsiders care about NexSON?

### ISSUE THREAD

**Issue by rvosa** [OpenTreeOfLife/phylesystem-api#215]
Hi all,

I have reason to want to be able to roundtrip my data to and from JSON, and I have the option of adopting NexSON (or doing whatever suits me). Is it worth going with NexSON? Aside from vocabularies and their terms, how stable is the core right now?

Thanks!

**Comment by mtholder** [comment]
We haven't changed the version that we store for a while... so I guess that indicates some level of stability.

That being said, we should be able to transform our docs to other formats pretty easily. So, I'm not sure that there is a huge benefit to adopting what open tree uses. In fact if you come up with something nice we might adopt it.

The form that we currently store (NexSON v1.2.1) is not great wrt a few of things:

  1. it maintains the convention (from NEXUS via NeXML) of having groups of OTU groups; and groups of tree groups, etc.  I think that it would be much cleaner to have one set of OTUs, and store the info needed to write multiple OTU blocks as some form of annotation.

  2. the tree structure used means that rerooting causes lots of edits to a file. Not a big deal really, but since we store the JSON in git it leads to unnecessarily messy diffs caused by simple reroot operation.

  3. we only deal with annotations, otus, and trees. We've never tackled other "blocks" in the NEXUS lingo.


I don't think we have other regrets about what we are using, but others may chime in with differing takes on that point.

**Comment by rvosa** [comment]
Hi Mark,

thanks for the reply. Good to hear that you're all basically married to NexSON at this stage, it's probably stable because changing it would break too many things, right? :)

1. I agree, the taxa blocks were a bad decision in NeXML as well. You can tell from the pathologies around chained references, where a container, like a character matrix or a tree block, refers to a taxa block, and the things in that container must refer to taxa inside THAT taxa block. This can't actually be validated in XML schema languages, and so some programs (like DendroScope) have exploited this by referring to an empty taxa block and not have any of the tree tips refer to anything, basically just to get the validator to shut up.

2. There's probably reasons why this doesn't work, but I can imagine that you serialize your tree with a basal trichotomy (like in the Newick convention for unrooted trees) and then apply the [`root="true"`](https://github.com/OpenTreeOfLife/phylostylotastic/blob/master/design/viz_targets_exercise/remapped.xml#L17) attribute to whatever you want the root to be. In principle, you could keep the same topology and write it out in almost the exact same way (apart from the attribute), pass it through a JSON indenter, and it should give you cleaner diffs, no?

3. I don't think there's that much else to care about, unless we're still interested in distance matrices. NOTES, SETS and ASSUMPTIONS seem like annotations to me.

**Comment by mtholder** [comment]
We definitely need something that allows flexible annotation of OTUs and elements of trees (nodes, edges, the tree itself as unique piece of data). So we are married to that.

I think that the vast majority of open tree interactions with the format that we are currently calling open tree NexSON 1.2.1 passes through a single library. The JavaScript front end never ported over to using the most recent form, so we rely on on the fly translation to a different form of JSON for the curation of phylogenetic inputs. The supertree pipeline uses the same library to export newick.

Which is a long way of saying: we could actually adopt a new format fairly painlessly, but adding functionality to our python library to translate on the fly to the other formats that we use.

wrt to specifics:

point 2: I agree with your response. However, the 1.2.1 (see [our wiki](https://github.com/OpenTreeOfLife/phylesystem-api/wiki/HoneyBadgerFish) page) for ugly details uses a different format for the tree structure which makes it more complex than reassigning the root attribute. 

point 3: note that we don't even store the equivalent of CHARACTERS / DATA blocks.

**Comment by rvosa** [comment]
Ok, thanks. I like your mapping better than the "standard" badgerfish,
especially for unpacking meta elements - so I might go with it. I am going
to ignore your threat that you "could actually adopt a new format fairly
painlessly".

BTW, caveat number 2 on the wiki isn't completely true, in the sense that
at least Java would very much like to know what it is going to be parsing
(as in Integer.parseInt() and friends) so in that universe it kind of
matters what xsd: type is specified.

Anyway, thanks for sharing your thoughts. Please go ahead and close this
issue.
